<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ page import="jb.model.TjbAssets" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<script type="text/javascript">
	$(function() {
		parent.$.messager.progress('close');		
	});
</script>
<div class="easyui-layout" data-options="fit:true,border:false">
	<div data-options="region:'center',border:false">
		<table class="table table-hover table-condensed">
				<tr>	
					<th><%=TjbAssets.ALIAS_ASSET_NUMBER%></th>	
					<td>
						${jbAssets.assetNumber}							
					</td>							
					<th><%=TjbAssets.ALIAS_FIRST_CATEGORY%></th>	
					<td>
						${jbAssets.firstCategory}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_SECOND_CATEGORY%></th>	
					<td>
						${jbAssets.secondCategory}							
					</td>							
					<th><%=TjbAssets.ALIAS_DESCRIPTION%></th>	
					<td>
						${jbAssets.description}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_FACTORY%></th>	
					<td>
						${jbAssets.factory}							
					</td>							
					<th><%=TjbAssets.ALIAS_ASSET_TYPE%></th>	
					<td>
						${jbAssets.assetType}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_SERIAL_NUMBER%></th>	
					<td>
						${jbAssets.serialNumber}							
					</td>							
					<th><%=TjbAssets.ALIAS_LOCATION%></th>	
					<td>
						${jbAssets.location}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_DEPT_ID%></th>	
					<td>
						${jbAssets.deptId}							
					</td>							
					<th><%=TjbAssets.ALIAS_PRINCIPAL%></th>	
					<td>
						${jbAssets.principal}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_BUY_DATE%></th>	
					<td>
						${jbAssets.buyDate}							
					</td>							
					<th><%=TjbAssets.ALIAS_MAKE_DATE%></th>	
					<td>
						${jbAssets.makeDate}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_SUPPLIER%></th>	
					<td>
						${jbAssets.supplier}							
					</td>							
					<th><%=TjbAssets.ALIAS_SUPPLIER_PHONE%></th>	
					<td>
						${jbAssets.supplierPhone}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_MEASURE%></th>	
					<td>
						${jbAssets.measure}							
					</td>							
					<th><%=TjbAssets.ALIAS_WEIGHT%></th>	
					<td>
						${jbAssets.weight}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_STANDARD_POWER%></th>	
					<td>
						${jbAssets.standardPower}							
					</td>							
					<th><%=TjbAssets.ALIAS_ICON%></th>	
					<td>
						${jbAssets.icon}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_PARENT_ID%></th>	
					<td>
						${jbAssets.parentId}							
					</td>							
					<th><%=TjbAssets.ALIAS_ROOM_AREA_ID%></th>	
					<td>
						${jbAssets.roomAreaId}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_SCOPE%></th>	
					<td>
						${jbAssets.scope}							
					</td>							
					<th><%=TjbAssets.ALIAS_UPLACE%></th>	
					<td>
						${jbAssets.uplace}							
					</td>							
				</tr>		
				<tr>	
					<th><%=TjbAssets.ALIAS_UID%></th>	
					<td>
						${jbAssets.uid}							
					</td>							
					<th><%=TjbAssets.ALIAS_ADDTIME%></th>	
					<td>
						${jbAssets.addtime}							
					</td>							
				</tr>		
		</table>
	</div>
</div>